### ISSUE TITLE
only "turn on" and "turn off" works well,  " auto, sleep, favourite"mode doesn't work

### ISSUE THREAD

**Issue by superwangmeng** [mypalg/mi-airfresh#2]
hi, thanks for your contribution, it works not very well, only "turn on" and "turn off" works well,  " auto, sleep, favourite" doesn't work,but in Mijia app, if you choose " auto, sleep, favourite",it works and the status will deliver to the homeassistant and Homekit .could you fix it, thanks very much.

**Comment by superwangmeng** [comment]
there is the log:

ogger: homeassistant.core
Source: components/system_log/__init__.py:97
First occurred: 下午9:02:37 (2 occurrences)
Last logged: 下午9:02:40

Error executing service: <ServiceCall fan.set_speed (c:6aa3226c941c48589d3ff7f857c8eaaa): entity_id=['fan.mi_jia_xin_feng_ji'], speed=Sleep>
Error executing service: <ServiceCall fan.set_speed (c:9eb5fde6dae141baa7347e7b8458cf06): entity_id=['fan.mi_jia_xin_feng_ji'], speed=Favourite>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 177, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 177, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 177, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 177, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mi-airfresh/fan.py", line 283, in _try_command
    partial(self._device.send, *args, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 124, in send
    return self._protocol.send(command, parameters, retry_count)
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 215, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 215, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 215, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 218, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1276, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/mi-airfresh/fan.py", line 331, in async_set_speed
    "set_mode", OperationMode[speed.title()].value)
  File "/config/custom_components/mi-airfresh/fan.py", line 296, in send_raw_cmd
    result = await self._try_command(mask_error, command, parameters)
  File "/config/custom_components/mi-airfresh/fan.py", line 289, in _try_command
    _LOGGER.error(mask_error, exc)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 181, in emit
    record, stack, _figure_out_source(record, stack, self.hass)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 97, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by superwangmeng** [comment]
and there is another log about homekit:
日志详细信息（ WARNING ）
Logger: homeassistant.components.homekit.util
Source: components/homekit/util.py:304
Integration: HomeKit 桥接器 (documentation, issues)
First occurred: 下午8:57:48 (1 occurrences)
Last logged: 下午8:57:48

['Off', 'Auto', 'Sleep', 'Favourite'] does not contain the speed setting off as its first element. Assuming that Off is equivalent to 'off'.

**Comment by mypal** [comment]
What's the model of your device? My device is dmake.airfresh.t2017 and works well. The version of firework is the latest——2.1.3.0016

**Comment by superwangmeng** [comment]
@mypal I update the firework to 2.1.3.0016,it works well,thank you very much。
